apiVersion: v2
name: hipster-shop
description: A Helm chart for Kubernetes

type: application
version: 0.2.0
appVersion: "1.16.0"

dependencies:
- name: frontend
  version: 0.1.0
  repository: "file://../frontend"
- name: redis
  version: "15.5.3"
  repository: "https://charts.bitnami.com/bitnami"
