apiVersion: v1
kind: Pod
metadata:
  name: "web"
  labels:
    lang: python
spec:
  containers:
  - name: "web"
    image: "antik9/k8s-otus-web:0.1"
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: "init"
    image: "busybox:1.31.0"
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
